### PR TITLE
Fix study-webidl: re-entrance and exposure. Add first tests

### LINKED ISSUE #314: Web IDL validation: check on lack of `Exposed` needs fixing
Check on `mainExposure` looks for a falsy value, but `getExposure` returns an empty array at worst, so code won't ever detect missing exposure in practice:

https://github.com/w3c/strudy/blob/0eae9112c097f2c882f7fb77286e6326831bcf82/src/lib/study-webidl.js#L85

https://github.com/w3c/strudy/blob/0eae9112c097f2c882f7fb77286e6326831bcf82/src/lib/study-webidl.js#L49-L51

Also, code will crash if an interface definition references a `Global` that is not defined anywhere.

### PR DESCRIPTION
**Pull request by tidoust**
The report object was global, so a second call to studyWebIdl would not forget about previous results.

Also fixes #314.

First few tests added.

### CODE REVIEW

File: test/study-webidl.js [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+        nightly: { repository: 'https://github.com/w3c/spec' },
+        idl
+      }
+    ];
+  }
+
+  it('reports no anomaly if IDL is valid', async () => {
+    const crawlResult = toCrawlResult(
+`[Global=Window,Exposed=*]
+interface valid {};`);
```
Comment (dontcallmedom) [inline test/study-webidl.js:27]:
```suggestion
interface Valid {};`);
```
At some point I assume we'll check naming conventions that require interfaces to be capitalized, so we may as well use a valid name :)
